"""
routing_transparency — l3mcore plugin

Appends a small informational footer to each response indicating which expert
handled the request and the router's confidence score.  The footer is purely
cosmetic and can be toggled or customised entirely through config.json.

Hook used: after_generation(response, expert_label)

config.json keys (all optional, under "routing_transparency"):
  enabled      : bool   — master switch.  Default: true.
  show_score   : bool   — whether to include the confidence score. Default: true.
  show_method  : bool   — whether to show how routing was resolved. Default: false.
  separator    : str    — separator line printed before the footer. Default: "---".
  label        : str    — prefix text. Default: "🧠 Routed to".

Security notes:
  - The expert_label coming from the core has already been validated by the
    plugin_manager (it went through get_expert_config before execution).
    We still sanitise it here as a second line of defence.
  - No user input reaches this hook; only the generated response (str) and the
    internal expert label (str).
  - All config values are type-checked and length-capped before use.
"""

import re
import threading

# ---------------------------------------------------------------------------
# Module-level state (populated lazily on first call)
# ---------------------------------------------------------------------------
_config_lock = threading.Lock()
_cached_cfg: dict | None = None

_SAFE_LABEL_RE = re.compile(r'^[a-zA-Z0-9_\-]{1,64}$')
_MAX_SEPARATOR_LEN = 80
_MAX_LABEL_LEN = 60


def _load_config() -> dict:
    """
    Reads the 'routing_transparency' section from config.json via the l3mcore
    ConfigManager singleton.  Falls back to safe defaults if anything goes wrong.
    """
    defaults = {
        "enabled":     True,
        "show_score":  True,
        "show_method": False,
        "separator":   "---",
        "label":       "🧠 Routed to",
    }
    try:
        # Import here to avoid coupling at module load time
        from modules.config_manager import ConfigManager
        cfg_raw = ConfigManager().get("routing_transparency", {})
        if not isinstance(cfg_raw, dict):
            return defaults

        merged = dict(defaults)

        if isinstance(cfg_raw.get("enabled"), bool):
            merged["enabled"] = cfg_raw["enabled"]
        if isinstance(cfg_raw.get("show_score"), bool):
            merged["show_score"] = cfg_raw["show_score"]
        if isinstance(cfg_raw.get("show_method"), bool):
            merged["show_method"] = cfg_raw["show_method"]

        sep = cfg_raw.get("separator", defaults["separator"])
        if isinstance(sep, str) and 0 < len(sep) <= _MAX_SEPARATOR_LEN:
            # Strip any control characters
            merged["separator"] = re.sub(r'[\x00-\x1f\x7f]', '', sep)[:_MAX_SEPARATOR_LEN]

        lbl = cfg_raw.get("label", defaults["label"])
        if isinstance(lbl, str) and 0 < len(lbl) <= _MAX_LABEL_LEN:
            merged["label"] = re.sub(r'[\x00-\x1f\x7f]', '', lbl)[:_MAX_LABEL_LEN]

        return merged
    except Exception:
        return defaults


def _get_config() -> dict:
    """Returns cached config, refreshing it if config.json has changed."""
    global _cached_cfg
    with _config_lock:
        if _cached_cfg is None:
            _cached_cfg = _load_config()
        return _cached_cfg


def _invalidate_cache() -> None:
    """Called when hot-reload is detected (optional utility)."""
    global _cached_cfg
    with _config_lock:
        _cached_cfg = None


# ---------------------------------------------------------------------------
# Hook
# ---------------------------------------------------------------------------

def after_generation(response: str, expert_label: str = "unknown") -> str:
    """
    Appends a routing footer to the model response.

    Parameters
    ----------
    response     : str  — the full text generated by the expert model.
    expert_label : str  — internal label of the expert that was used.

    Returns
    -------
    str — the original response with the footer appended, or unchanged if
          the plugin is disabled or an error occurs.
    """
    try:
        cfg = _get_config()

        if not cfg.get("enabled", True):
            return response

        # --- Sanitise the expert label before it ever touches the output ----
        if not isinstance(expert_label, str):
            expert_label = "unknown"

        # Keep only safe characters; reject anything that looks injected
        if not _SAFE_LABEL_RE.match(expert_label):
            expert_label = "unknown"

        # --- Build footer ---------------------------------------------------
        sep = cfg.get("separator", "---")
        lbl = cfg.get("label", "🧠 Routed to")

        footer_parts = [f"\n\n{sep}", f"{lbl}: **{expert_label}**"]

        if cfg.get("show_score") and _last_score.get(expert_label) is not None:
            score = _last_score.get(expert_label, 0.0)
            footer_parts.append(f"(confidence: {score:.0%})")

        footer = " ".join(footer_parts)

        return response + footer

    except Exception:
        # Never break the response pipeline
        return response


# ---------------------------------------------------------------------------
# Score injection helper — called by the core via a lightweight side-channel
# ---------------------------------------------------------------------------
# The core does not pass the score to after_generation by default.
# We store the last score per label in a module-level dict so the footer can
# display it when available.  This is populated by the companion route endpoint
# introduced in api_server.py (/v1/route) and by the transparency_score_hint
# helper below which api_server.py calls right after routing resolves.
#
# Thread safety: dict operations on CPython are GIL-protected for simple
# gets/sets, but we use a lock to be explicit and portable.

_score_lock = threading.Lock()
_last_score: dict[str, float] = {}


def set_route_score(label: str, score: float) -> None:
    """
    Called by api_server.py immediately after routing to store the confidence
    score so the footer can display it.

    Parameters
    ----------
    label : str   — expert label that was selected.
    score : float — confidence score in [0, 1].
    """
    if not isinstance(label, str) or not isinstance(score, (int, float)):
        return
    if not _SAFE_LABEL_RE.match(label):
        return
    score = max(0.0, min(1.0, float(score)))
    with _score_lock:
        _last_score[label] = score
